INSERT INTO `stations_temp` (
    `id`,
    `country`,
    `region`,
    `name`,
    `name_alt`,
    `national_id`,
    `wmo`,
    `icao`,
    `iata`,
    `ghcn`,
    `wban`,
    `usaf`,
    `latitude`,
    `longitude`,
    `altitude`,
    `tz`
)
VALUES (
    :id,
    :country,
    :region,
    :name,
    :name_alt,
    :national_id,
    :wmo,
    :icao,
    :iata,
    :ghcn,
    :wban,
    :usaf,
    :lat,
    :lon,
    :elevation,
    :tz
)
ON DUPLICATE KEY UPDATE
    `id` = VALUES(`id`),
    `country` = VALUES(`country`),
    `region` = VALUES(`region`),
    `name` = VALUES(`name`),
    `name_alt` = VALUES(`name_alt`),
    `national_id` = VALUES(`national_id`),
    `wmo` = VALUES(`wmo`),
    `icao` = VALUES(`icao`),
    `iata` = VALUES(`iata`),
    `ghcn` = VALUES(`ghcn`),
    `wban` = VALUES(`wban`),
    `usaf` = VALUES(`usaf`),
    `latitude` = VALUES(`latitude`),
    `longitude` = VALUES(`longitude`),
    `altitude` = VALUES(`altitude`),
    `tz` = VALUES(`tz`)
